spring:

  apikey:
    uuid: 2409aeab-9179-4ad7-b400-891ce338b57a
  mail:
    host: ${SMTP_EMAIL_PROVIDER}
    port: ${SMTP_EMAIL_PROVIDER_PORT}
    username: ${SMTP_EMAIL_USERNAME}
    password: ${SMTP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # solve problem in swagger 'documentationPluginsBootstrapper'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true
  cache:
    type: redis
  redis:
    host: redis-guardian.guardian_guardian-net
    port: 16379
server:
  tomcat:
    threads:
      max: 10

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

guardian:
  admin:
    magicSeed: B7CdeU3QtR1FQctrSV0JatNEcGeAaFUfSBW2XdDIgpF2eMmUIM
  api:
    url: http://localhost:8081 # ou a URL do serviço real

email:
  send-to-admin: false
  admin-email-account: ${MAIL_ADMIN}
  from-mail: ${MAIL_SEND_FROM}