version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq-opensource
    hostname: opensource-labs
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_opensource:/var/lib/rabbitmq/
    networks:
      - opensource-net
  redis-opensource:
    container_name: redis-opensource
    image: redis:7.2.3-alpine
    ports:
      - "16379:6379"
    networks:
      - opensource-net
    volumes:
      - redis_data_guardian:/data
  pg-guardian:
    container_name: pg-guardian
    image: postgres:9.6
    ports:
      - "5120:5432"
    networks:
      - opensource-net
    environment:
      - POSTGRES_DB=guardian
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_opensource:/var/lib/postgresql
      - postgresql_data_guardian:/var/lib/postgresql/data
  pg-preferences:
    container_name: pg-preferences
    image: postgres:9.6
    ports:
      - "5121:5432"
    networks:
      - opensource-net
    environment:
      - POSTGRES_DB=preferences
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_opensource:/var/lib/postgresql
      - postgresql_data_preferences:/var/lib/postgresql/data
  pg-notifier:
    container_name: pg-notifier
    image: postgres:9.6
    ports:
      - "5122:5432"
    networks:
      - opensource-net
    environment:
      - POSTGRES_DB=notifier
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_opensource:/var/lib/postgresql
      - postgresql_data_notifier:/var/lib/postgresql/data
  pg-reminder:
    container_name: pg-reminder
    image: postgres:9.6
    ports:
      - "5123:5432"
    networks:
      - opensource-net
    environment:
      - POSTGRES_DB=reminder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_opensource:/var/lib/postgresql
      - postgresql_data_reminder:/var/lib/postgresql/data
  pg-bei:
    container_name: pg-bei
    image: postgres:9.6
    ports:
      - "5124:5432"
    networks:
      - opensource-net
    environment:
      - POSTGRES_DB=bei
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_opensource:/var/lib/postgresql
      - postgresql_data_bei:/var/lib/postgresql/data
  pg-reaction:
    container_name: pg-reaction
    image: postgres:9.6
    ports:
      - "5126:5432"
    networks:
      - opensource-net
    environment:
      - POSTGRES_DB=reaction
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_opensource:/var/lib/postgresql
      - postgresql_data_reaction:/var/lib/postgresql/data
  pg-brcities:
    container_name: pg-brcities
    image: postgres:9.6
    ports:
      - "5127:5432"
    networks:
      - opensource-net
    environment:
      - POSTGRES_DB=brcities
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_opensource:/var/lib/postgresql
      - postgresql_data_brcities:/var/lib/postgresql/data
  pg-mailsender:
    container_name: pg-mailsender
    image: postgres:9.6
    ports:
      - "5129:5432"
    networks:
      - opensource-net
    environment:
      - POSTGRES_DB=mailsender
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_opensource:/var/lib/postgresql
      - postgresql_data_mailsender:/var/lib/postgresql/data
  app-guardian:
    container_name: app-guardian
    image: juliovitorino/guardian:latest
    ports:
      - "9090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-guardian:5432/guardian
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - opensource-net
    depends_on:
      - pg-guardian
      - redis-opensource
  app-preferences:
    container_name: app-preferences
    image: juliovitorino/preferences:latest
    ports:
      - "9091:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-preferences:5432/preferences
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - opensource-net
    depends_on:
      - pg-preferences
      - redis-opensource
  app-bei:
    container_name: app-bei
    image: juliovitorino/bei:latest
    ports:
      - "9092:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-bei:5432/bei
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - opensource-net
    depends_on:
      - pg-bei
      - redis-opensource
  app-notifier:
    container_name: app-notifier
    image: juliovitorino/notifier:latest
    ports:
      - "9093:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-notifier:5432/notifier
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - opensource-net
    depends_on:
      - pg-notifier
      - redis-opensource
      - rabbitmq
networks:
  opensource-net:

volumes:
  postgresql_opensource:
  postgresql_data_guardian:
  postgresql_data_preferences:
  postgresql_data_notifier:
  postgresql_data_reminder:
  postgresql_data_bei:
  postgresql_data_reaction:
  postgresql_data_brcities:
  postgresql_data_mailsender:
  redis_data_guardian:
  rabbitmq_data_opensource:

