spring:
  application:
    name: guardian-app

  # solve problem in swagger 'documentationPluginsBootstrapper'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://pg-guardian-instance.cev4hwwunwmk.sa-east-1.rds.amazonaws.com:5432/guardian_db
    username: pgguardian
    password: EiAqAlZb0qRKegk
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true;
  cache:
    type: redis
  redis:
    host: redis-guardian.guardian_guardian-net
    port: 16379
server:
  tomcat:
    threads:
      max: 10

guardian:
  admin:
    magicSeed: B7CdeU3QtR1FQctrSV0JatNEcGeAaFUfSBW2XdDIgpF2eMmUIM