spring:
  application:
    name: preferences-app

  # solve problem in swagger 'documentationPluginsBootstrapper'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5121/preferences
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true;
  cache:
    type: redis
  redis:
    host: redis-guardian.guardian_guardian-net
    port: 6379

server:
  tomcat:
    threads:
      max: 10

