--liquibase formatted sql

--changeset julio.vitorino:2025-08-29_01-insert-modalities
--comment Insert default modalities
INSERT INTO modality (id, name_pt, name_en, name_es) VALUES
(1, 'Musculação', 'Bodybuilding', 'Musculación'),
(2, 'Treinamento Funcional', 'Functional Training', 'Entrenamiento Funcional'),
(3, 'Yoga', 'Yoga', 'Yoga'),
(4, 'Pilates', 'Pilates', 'Pilates'),
(5, 'CrossFit', 'CrossFit', 'CrossFit'),
(6, 'Calistenia', 'Calisthenics', 'Calistenia'),
(7, 'Spinning', 'Spinning', 'Spinning'),
(8, 'HIIT', 'HIIT', 'HIIT'),
(9, 'Corrida', 'Running', 'Correr'),
(10, 'Caminhada', 'Walking', 'Caminata'),
(11, 'Alongamento', 'Stretching', 'Estiramiento'),
(12, 'Mobilidade Articular', 'Joint Mobility', 'Movilidad Articular'),
(13, 'Zumba', 'Zumba', 'Zumba'),
(14, 'Step', 'Step', 'Step'),
(15, 'Jump', 'Jump', 'Jump'),
(16, 'Boxe', 'Boxing', 'Boxeo'),
(17, 'Muay Thai', 'Muay Thai', 'Muay Thai'),
(18, 'Jiu-Jitsu', 'Jiu-Jitsu', 'Jiu-Jitsu'),
(19, 'Judô', 'Judo', 'Judo'),
(20, 'Karatê', 'Karate', 'Karate'),
(21, 'Taekwondo', 'Taekwondo', 'Taekwondo'),
(22, 'Capoeira', 'Capoeira', 'Capoeira'),
(23, 'Natação', 'Swimming', 'Natación'),
(24, 'Hidroginástica', 'Water Aerobics', 'Aquagym'),
(25, 'Remo Indoor', 'Indoor Rowing', 'Remo Indoor'),
(26, 'Escalada Indoor', 'Indoor Climbing', 'Escalada Indoor'),
(27, 'TRX', 'Suspension Training', 'Entrenamiento en Suspensión'),
(28, 'Slackline', 'Slackline', 'Slackline'),
(29, 'Parkour', 'Parkour', 'Parkour'),
(30, 'Escalada', 'Climbing', 'Escalada'),
(31, 'Patinação', 'Skating', 'Patinaje'),
(32, 'Ciclismo', 'Cycling', 'Ciclismo'),
(33, 'Basquete', 'Basketball', 'Baloncesto'),
(34, 'Futebol', 'Soccer', 'Fútbol'),
(35, 'Futsal', 'Indoor Soccer', 'Fútbol Sala'),
(36, 'Handebol', 'Handball', 'Balonmano'),
(37, 'Vôlei', 'Volleyball', 'Voleibol'),
(38, 'Beach Tennis', 'Beach Tennis', 'Tenis Playa'),
(39, 'Tênis', 'Tennis', 'Tenis'),
(40, 'Paddle', 'Paddle', 'Pádel'),
(41, 'Esgrima', 'Fencing', 'Esgrima'),
(42, 'Ginástica Rítmica', 'Rhythmic Gymnastics', 'Gimnasia Rítmica'),
(43, 'Ginástica Artística', 'Artistic Gymnastics', 'Gimnasia Artística'),
(44, 'Ginástica Acrobática', 'Acrobatic Gymnastics', 'Gimnasia Acrobática'),
(45, 'Powerlifting', 'Powerlifting', 'Powerlifting'),
(46, 'Strongman', 'Strongman', 'Strongman'),
(47, 'Levantamento Olímpico', 'Olympic Weightlifting', 'Halterofilia Olímpica'),
(48, 'Corrida de Obstáculos', 'Obstacle Course Racing', 'Carreras de Obstáculos'),
(49, 'Dança Contemporânea', 'Contemporary Dance', 'Danza Contemporánea'),
(50, 'Balé', 'Ballet', 'Ballet'),
(51, 'Jazz Dance', 'Jazz Dance', 'Danza Jazz'),
(52, 'Street Dance', 'Street Dance', 'Baile Urbano'),
(53, 'Pole Dance', 'Pole Dance', 'Pole Dance'),
(54, 'Ginástica Localizada', 'Localized Gymnastics', 'Gimnasia Localizada'),
(55, 'Treinamento Militar', 'Military Training', 'Entrenamiento Militar'),
(56, 'Corrida de Rua', 'Street Running', 'Carrera Callejera'),
(57, 'Mountain Bike', 'Mountain Biking', 'Ciclismo de Montaña'),
(58, 'Skate', 'Skateboarding', 'Skateboarding'),
(59, 'Surfe', 'Surfing', 'Surf'),
(60, 'Bodyboard', 'Bodyboarding', 'Bodyboard'),
(61, 'Windsurf', 'Windsurfing', 'Windsurf'),
(62, 'Kitesurf', 'Kitesurfing', 'Kitesurf'),
(63, 'Canoagem', 'Canoeing', 'Piragüismo'),
(64, 'Escalada em Rocha', 'Rock Climbing', 'Escalada en Roca'),
(65, 'Tiro com Arco', 'Archery', 'Tiro con Arco'),
(66, 'Corrida em Trilha', 'Trail Running', 'Carrera de Montaña'),
(67, 'Corrida de Orientação', 'Orienteering', 'Orientación'),
(68, 'Equitação', 'Horse Riding', 'Equitación'),
(69, 'Atletismo', 'Athletics', 'Atletismo'),
(70, 'Marcha Atlética', 'Race Walking', 'Marcha Atlética'),
(71, 'Salto com Vara', 'Pole Vault', 'Salto con Pértiga'),
(72, 'Salto em Altura', 'High Jump', 'Salto de Altura'),
(73, 'Arremesso de Peso', 'Shot Put', 'Lanzamiento de Bala'),
(74, 'Lançamento de Dardo', 'Javelin Throw', 'Lanzamiento de Jabalina'),
(75, 'Lançamento de Disco', 'Discus Throw', 'Lanzamiento de Disco'),
(76, 'Corrida de Revezamento', 'Relay Race', 'Carrera de Relevo'),
(77, 'Treinamento Pós-Parto', 'Postpartum Training', 'Entrenamiento Postparto'),
(78, 'Treinamento Pré-Natal', 'Prenatal Training', 'Entrenamiento Prenatal'),
(79, 'Treinamento para Terceira Idade', 'Senior Training', 'Entrenamiento para Mayores'),
(80, 'Treinamento Infantil', 'Kids Training', 'Entrenamiento Infantil'),
(81, 'Treinamento Corporativo', 'Corporate Training', 'Entrenamiento Corporativo'),
(82, 'Reabilitação Física', 'Physical Rehabilitation', 'Rehabilitación Física'),
(83, 'Prevenção de Lesões', 'Injury Prevention', 'Prevención de Lesiones'),
(84, 'Condicionamento Físico', 'Physical Conditioning', 'Acondicionamiento Físico'),
(85, 'Core Training', 'Core Training', 'Entrenamiento de Core'),
(86, 'Resistência Cardiorrespiratória', 'Cardiorespiratory Endurance', 'Resistencia Cardiorrespiratoria'),
(87, 'Força Muscular', 'Muscular Strength', 'Fuerza Muscular'),
(88, 'Flexibilidade', 'Flexibility', 'Flexibilidad'),
(89, 'Velocidade', 'Speed', 'Velocidad'),
(90, 'Agilidade', 'Agility', 'Agilidad'),
(91, 'Coordenação Motora', 'Motor Coordination', 'Coordinación Motora'),
(92, 'Equilíbrio', 'Balance', 'Equilibrio'),
(93, 'Propriocepção', 'Proprioception', 'Propiocepción'),
(94, 'Biomecânica do Movimento', 'Movement Biomechanics', 'Biomecánica del Movimiento'),
(95, 'Análise Postural', 'Postural Analysis', 'Análisis Postural'),
(96, 'Ergonomia', 'Ergonomics', 'Ergonomía'),
(97, 'Psicomotricidade', 'Psychomotricity', 'Psicomotricidad'),
(98, 'Educação Física Escolar', 'School Physical Education', 'Educación Física Escolar'),
(99, 'Atividades Recreativas', 'Recreational Activities', 'Actividades Recreativas'),
(100, 'Jogos Cooperativos', 'Cooperative Games', 'Juegos Cooperativos'),
(101, 'Exergames', 'Exergames', 'Exergames'),
(102, 'Atividades ao Ar Livre', 'Outdoor Activities', 'Actividades al Aire Libre') ON CONFLICT DO NOTHING;
--rollback DELETE FROM modality WHERE id BETWEEN 1 AND 102;
