package br.com.jcv.security.guardian;

public enum RoleEnums {
    ADMIN_SUPER_POWER,
    GUARDIAN_REGISTER_APPLICATION,
    GUARDIAN_CREATE_ACCOUNT,
    GUARDIAN_DELETE_ACCOUNT,
    GUARDIAN_CREATE_ROLE,
    GUARDIAN_DELETE_APPLICATION,
    GUARDIAN_CREATE_GROUP,
    GUARDIAN_CREATE_GROUP_ROLE_RELATIONSHIP,
    GUARDIAN_CREATE_USER_ROLE_RELATIONSHIP,
    GUARDIAN_CREATE_GROUP_USER_RELATIONSHIP
}
