spring:
  application:
    name: mylab-app

  cloud:
    loadbalancer:
      ribbon:
        enable: true
  # solve problem in swagger 'documentationPluginsBootstrapper'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5127/brcities
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  threads:
    virtual:
      enabled: false;
  cache:
    type: redis
  redis:
    host: localhost
    port: 16379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  tomcat:
    threads:
      max: 8

